/**
 * Generated by figma2react — do not edit; re-run to update.
 * Hand-written stories belong in form-field.custom.stories.tsx, which
 * is never overwritten.
 */

import type { Meta, StoryObj } from '@storybook/react'
import { expectLayoutWithin } from './fidelity.js'
import { FormField } from './form-field.js'

const meta = {
  title: 'Design System/FormField',
  component: FormField,
  tags: ['autodocs'],
  parameters: {
    design: {
      type: 'figma',
      url: 'https://www.figma.com/design/uA3bE5ofr6BgRakJzudL4L/component?node-id=2-73',
    },
  },
} satisfies Meta<typeof FormField>

export default meta

type Story = StoryObj<typeof meta>

export const Default: Story = {
  args: {
    label: 'Label',
    placeholderText: 'Placeholder text',
  },
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}
