/**
 * Generated by figma2react — do not edit; re-run to update.
 * Hand-written stories belong in button.custom.stories.tsx, which
 * is never overwritten.
 *
 * Each variant is still its own component, so only the first can be `meta.component`;
 * the rest render explicitly. Collapsing variants into one component with a
 * prop union would remove that, and is not implemented.
 */

import type { Meta, StoryObj } from '@storybook/react'
import { expectLayoutWithin } from '../fidelity/assert.js'
import { ButtonPrimary } from './button-primary.js'
import { ButtonSecondary } from './button-secondary.js'
import { ButtonGhost } from './button-ghost.js'

const meta = {
  title: 'Design System/Button',
  component: ButtonPrimary,
  tags: ['autodocs'],
  parameters: {
    design: {
      type: 'figma',
      url: 'https://www.figma.com/design/uA3bE5ofr6BgRakJzudL4L/component?node-id=2-66',
    },
  },
} satisfies Meta<typeof ButtonPrimary>

export default meta

type Story = StoryObj<typeof meta>

export const Primary: Story = {
  args: {
    buttonLabel: 'Button Label',
  },
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}

export const Secondary: Story = {
  args: {
    buttonLabel: 'Button Label',
  },
  render: (args) => <ButtonSecondary {...args} />,
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}

export const Ghost: Story = {
  args: {
    buttonLabel: 'Button Label',
  },
  render: (args) => <ButtonGhost {...args} />,
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}
