import type { FontUsage, Token, TokenTable } from './collect.js'
import type { TokenKind } from './types.js'

/** CSS custom-property namespaces used by generated components. */
export const NAMESPACE: Record<TokenKind, string> = {
  color: '--color',
  spacing: '--spacing',
  radius: '--radius',
  fontSize: '--text',
  shadow: '--shadow',
  fontFamily: '--font',
}

const ORDER: TokenKind[] = ['color', 'fontFamily', 'fontSize', 'spacing', 'radius', 'shadow']

/**
 * Renders the token table as ordinary browser custom properties.
 */
export function emitThemeCss(table: TokenTable): string {
  const grouped = new Map<TokenKind, Token[]>()
  for (const token of table.tokens) {
    const list = grouped.get(token.kind) ?? []
    list.push(token)
    grouped.set(token.kind, list)
  }

  const blocks: string[] = []
  for (const kind of ORDER) {
    const tokens = grouped.get(kind)
    if (!tokens?.length) continue
    blocks.push(
      `  /* ${LABEL[kind]} */\n` +
        [...tokens]
          .sort((a, b) => a.name.localeCompare(b.name))
          .map((t) => `  ${NAMESPACE[kind]}-${t.name}: ${cssValue(kind, t.value)};`)
          .join('\n'),
    )
  }

  const header = `${WIRING}\n`
  if (blocks.length === 0) {
    return `${header}/* No design tokens found. Bind colours and spacing to Figma\n   Variables or Styles, then re-run to populate this file. */\n`
  }
  return `${header}:root {\n${blocks.join('\n\n')}\n}\n`
}

/**
 * Generated files get overwritten, so the import instructions live in the file.
 */
const WIRING = `/* Generated by figma2react - do not edit; re-run to update.
 *
 * Wire it up from your own stylesheet, in this order:
 *
 *   @import './tokens.css';
 */`

/**
 * A standalone stylesheet that loads the typefaces the theme names.
 *
 * It has to be its own file. A CSS `@import url(...)` is only valid before any
 * other rule, so one buried inside the theme file lands in the middle of the
 * bundle once the build inlines it — and is then dropped, silently, leaving a
 * page that renders in a fallback and looks fine to anyone who has the font
 * installed locally.
 */
export function emitFontCss(fonts: FontUsage[]): string {
  const url = googleFontsUrl(fonts)
  if (!url) return ''
  return (
    `/* Generated by figma2react - do not edit; re-run to update.\n` +
    ` *\n` +
    ` * Import this BEFORE anything else in the generated theme: a CSS @import\n` +
    ` * is only valid ahead of every other rule.\n` +
    ` *\n` +
    ` *   @import './fonts.css';\n` +
    ` *   @import './tokens.css';\n` +
    ` *\n` +
    ` * A <link> in your HTML head is faster and avoids the ordering rule:\n` +
    ` *   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n` +
    ` *   <link rel="stylesheet" href="${url}">\n` +
    ` *\n` +
    ` * A family that is not published on Google Fonts will not load. Self-host\n` +
    ` * it and replace this file.\n` +
    ` */\n` +
    `@import url('${url}');\n`
  )
}

/** Requests exactly the weights and italics the design draws in, nothing more. */
export function googleFontsUrl(fonts: FontUsage[]): string {
  if (fonts.length === 0) return ''
  const families = fonts.map((f) => {
    const name = f.family.replace(/\s+/g, '+')
    const anyItalic = f.styles.some((s) => s.italic)
    const axis = anyItalic
      ? `ital,wght@${f.styles.map((s) => `${s.italic ? 1 : 0},${s.weight}`).join(';')}`
      : `wght@${f.styles.map((s) => s.weight).join(';')}`
    return `family=${name}:${axis}`
  })

  return `https://fonts.googleapis.com/css2?${families.join('&')}&display=swap`
}

const LABEL: Record<TokenKind, string> = {
  color: 'Colours',
  spacing: 'Spacing',
  radius: 'Radii',
  fontSize: 'Type scale',
  shadow: 'Shadows',
  fontFamily: 'Typefaces',
}

/** Lengths read better as rem in a theme; colours pass through untouched. */
function cssValue(kind: TokenKind, value: string): string {
  if (kind === 'color' || kind === 'shadow' || kind === 'fontFamily') return value
  const px = /^(-?[\d.]+)px$/.exec(value)
  if (!px) return value
  const rem = Number(px[1]) / 16
  return `${Number(rem.toFixed(4))}rem`
}
