import type { FontUsage, Token, TokenTable } from './collect.js'
import type { TokenKind } from './types.js'

/** Tailwind v4 namespaces each theme key by what utilities it feeds. */
const NAMESPACE: Record<TokenKind, string> = {
  color: '--color',
  spacing: '--spacing',
  radius: '--radius',
  fontSize: '--text',
  shadow: '--shadow',
  fontFamily: '--font',
}

const ORDER: TokenKind[] = ['color', 'fontFamily', 'fontSize', 'spacing', 'radius', 'shadow']

export interface EmitCssOptions {
  /**
   * Prepend `@import 'tailwindcss'` so the file stands alone as a Tailwind
   * entry point.
   *
   * Off by default, and that default matters: Tailwind v4 roots its automatic
   * source detection at the directory holding the file that imports it, and
   * skips anything gitignored. A generated directory is usually both — so a
   * generated entry point silently scans nothing and emits no utilities. As a
   * fragment imported by the app's own stylesheet, the scan root stays where
   * the app is.
   */
  includeImport?: boolean
  /**
   * Emit a Google Fonts `@import` for the typefaces the design uses.
   *
   * On by default: without it the theme names a family that nothing loads, so
   * the page renders in a fallback on any machine that happens not to have the
   * font installed — and does so silently, looking correct to whoever built it.
   */
  fontImport?: boolean
}

/**
 * Renders the token table as a Tailwind v4 `@theme` block. Every entry here
 * turns into real utilities: `--color-surface-raised` gives `bg-surface-raised`,
 * `text-surface-raised`, `border-surface-raised`, and so on.
 */
export function emitThemeCss(table: TokenTable, options: EmitCssOptions = {}): string {
  const grouped = new Map<TokenKind, Token[]>()
  for (const token of table.tokens) {
    const list = grouped.get(token.kind) ?? []
    list.push(token)
    grouped.set(token.kind, list)
  }

  const blocks: string[] = []
  for (const kind of ORDER) {
    const tokens = grouped.get(kind)
    if (!tokens?.length) continue
    blocks.push(
      `  /* ${LABEL[kind]} */\n` +
        [...tokens]
          .sort((a, b) => a.name.localeCompare(b.name))
          .map((t) => `  ${NAMESPACE[kind]}-${t.name}: ${cssValue(kind, t.value)};`)
          .join('\n'),
    )
  }

  const header = options.includeImport ? "@import 'tailwindcss';\n\n" : `${WIRING}\n`
  if (blocks.length === 0) {
    return `${header}/* No design tokens found. Bind colours and spacing to Figma\n   Variables or Styles, then re-run to populate this file. */\n`
  }
  return `${header}@theme {\n${blocks.join('\n\n')}\n}\n`
}

/**
 * Generated files get overwritten, so the instructions have to live in the file
 * itself — and `@source` has to be spelled out because a generated directory is
 * very often gitignored, which takes it out of Tailwind's automatic scan.
 */
const WIRING = `/* Generated by figma2react - do not edit; re-run to update.
 *
 * Wire it up from your own stylesheet, in this order:
 *
 *   @import 'tailwindcss';
 *   @import './tokens.css';
 *
 * Synthesised names deliberately follow Tailwind's own scale, so an entry here
 * may shadow a built-in: --color-blue-600 replaces Tailwind's blue-600 app-wide.
 * That is usually what you want. It also means forgetting the import above is
 * silent - the classes still resolve, to Tailwind's colours instead of yours.
 *
 * If the generated directory is gitignored, Tailwind will not scan it and none
 * of these classes reach your bundle - the build still succeeds, it just has no
 * styles. Add a source line next to those imports, and note it must be an
 * explicit glob; a bare directory path does not override gitignore:
 *
 *   @source './generated/*.tsx';
 */`

/**
 * A standalone stylesheet that loads the typefaces the theme names.
 *
 * It has to be its own file. A CSS `@import url(...)` is only valid before any
 * other rule, so one buried inside the theme file lands in the middle of the
 * bundle once the build inlines it — and is then dropped, silently, leaving a
 * page that renders in a fallback and looks fine to anyone who has the font
 * installed locally.
 */
export function emitFontCss(fonts: FontUsage[]): string {
  const url = googleFontsUrl(fonts)
  if (!url) return ''
  return (
    `/* Generated by figma2react - do not edit; re-run to update.\n` +
    ` *\n` +
    ` * Import this BEFORE anything else, including tailwindcss: a CSS @import\n` +
    ` * is only valid ahead of every other rule.\n` +
    ` *\n` +
    ` *   @import './fonts.css';\n` +
    ` *   @import 'tailwindcss';\n` +
    ` *   @import './tokens.css';\n` +
    ` *\n` +
    ` * A <link> in your HTML head is faster and avoids the ordering rule:\n` +
    ` *   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n` +
    ` *   <link rel="stylesheet" href="${url}">\n` +
    ` *\n` +
    ` * A family that is not published on Google Fonts will not load. Self-host\n` +
    ` * it and replace this file.\n` +
    ` */\n` +
    `@import url('${url}');\n`
  )
}

/** Requests exactly the weights and italics the design draws in, nothing more. */
export function googleFontsUrl(fonts: FontUsage[]): string {
  if (fonts.length === 0) return ''
  const families = fonts.map((f) => {
    const name = f.family.replace(/\s+/g, '+')
    const anyItalic = f.styles.some((s) => s.italic)
    const axis = anyItalic
      ? `ital,wght@${f.styles.map((s) => `${s.italic ? 1 : 0},${s.weight}`).join(';')}`
      : `wght@${f.styles.map((s) => s.weight).join(';')}`
    return `family=${name}:${axis}`
  })

  return `https://fonts.googleapis.com/css2?${families.join('&')}&display=swap`
}

const LABEL: Record<TokenKind, string> = {
  color: 'Colours',
  spacing: 'Spacing',
  radius: 'Radii',
  fontSize: 'Type scale',
  shadow: 'Shadows',
  fontFamily: 'Typefaces',
}

/** Lengths read better as rem in a theme; colours pass through untouched. */
function cssValue(kind: TokenKind, value: string): string {
  if (kind === 'color' || kind === 'shadow' || kind === 'fontFamily') return value
  const px = /^(-?[\d.]+)px$/.exec(value)
  if (!px) return value
  const rem = Number(px[1]) / 16
  return `${Number(rem.toFixed(4))}rem`
}
