import type { Token, TokenTable } from './collect.js'
import type { TokenKind } from './types.js'

/** Tailwind v4 namespaces each theme key by what utilities it feeds. */
const NAMESPACE: Record<TokenKind, string> = {
  color: '--color',
  spacing: '--spacing',
  radius: '--radius',
  fontSize: '--text',
  shadow: '--shadow',
}

const ORDER: TokenKind[] = ['color', 'spacing', 'radius', 'fontSize', 'shadow']

export interface EmitCssOptions {
  /**
   * Prepend `@import 'tailwindcss'` so the file stands alone as a Tailwind
   * entry point.
   *
   * Off by default, and that default matters: Tailwind v4 roots its automatic
   * source detection at the directory holding the file that imports it, and
   * skips anything gitignored. A generated directory is usually both — so a
   * generated entry point silently scans nothing and emits no utilities. As a
   * fragment imported by the app's own stylesheet, the scan root stays where
   * the app is.
   */
  includeImport?: boolean
}

/**
 * Renders the token table as a Tailwind v4 `@theme` block. Every entry here
 * turns into real utilities: `--color-surface-raised` gives `bg-surface-raised`,
 * `text-surface-raised`, `border-surface-raised`, and so on.
 */
export function emitThemeCss(table: TokenTable, options: EmitCssOptions = {}): string {
  const grouped = new Map<TokenKind, Token[]>()
  for (const token of table.tokens) {
    const list = grouped.get(token.kind) ?? []
    list.push(token)
    grouped.set(token.kind, list)
  }

  const blocks: string[] = []
  for (const kind of ORDER) {
    const tokens = grouped.get(kind)
    if (!tokens?.length) continue
    blocks.push(
      `  /* ${LABEL[kind]} */\n` +
        [...tokens]
          .sort((a, b) => a.name.localeCompare(b.name))
          .map((t) => `  ${NAMESPACE[kind]}-${t.name}: ${cssValue(kind, t.value)};`)
          .join('\n'),
    )
  }

  const header = options.includeImport ? "@import 'tailwindcss';\n\n" : `${WIRING}\n`
  if (blocks.length === 0) {
    return `${header}/* No design tokens found. Bind colours and spacing to Figma\n   Variables or Styles, then re-run to populate this file. */\n`
  }
  return `${header}@theme {\n${blocks.join('\n\n')}\n}\n`
}

/**
 * Generated files get overwritten, so the instructions have to live in the file
 * itself — and `@source` has to be spelled out because a generated directory is
 * very often gitignored, which takes it out of Tailwind's automatic scan.
 */
const WIRING = `/* Generated by figma2react - do not edit; re-run to update.
 *
 * Wire it up from your own stylesheet, in this order:
 *
 *   @import 'tailwindcss';
 *   @import './tokens.css';
 *
 * If the generated directory is gitignored, Tailwind will not scan it and none
 * of these classes reach your bundle - the build still succeeds, it just has no
 * styles. Add a source line next to those imports, and note it must be an
 * explicit glob; a bare directory path does not override gitignore:
 *
 *   @source './generated/*.tsx';
 */`

const LABEL: Record<TokenKind, string> = {
  color: 'Colours',
  spacing: 'Spacing',
  radius: 'Radii',
  fontSize: 'Type scale',
  shadow: 'Shadows',
}

/** Lengths read better as rem in a theme; colours pass through untouched. */
function cssValue(kind: TokenKind, value: string): string {
  if (kind === 'color' || kind === 'shadow') return value
  const px = /^(-?[\d.]+)px$/.exec(value)
  if (!px) return value
  const rem = Number(px[1]) / 16
  return `${Number(rem.toFixed(4))}rem`
}
