/**
 * Generated by figma2react — do not edit; re-run to update.
 * Hand-written stories belong in button.custom.stories.tsx, which
 * is never overwritten.
 *
 * Each variant is still its own component, so only the first can be `meta.component`;
 * the rest render explicitly. Collapsing variants into one component with a
 * prop union would remove that, and is not implemented.
 */

import type { Meta, StoryObj } from '@storybook/react'
import { expectLayoutWithin } from './fidelity.js'
import { ButtonPrimaryDefault } from './button-primary-default.js'
import { ButtonPrimaryHover } from './button-primary-hover.js'
import { ButtonSecondaryDefault } from './button-secondary-default.js'
import { ButtonSecondaryHover } from './button-secondary-hover.js'
import { ButtonGhostDefault } from './button-ghost-default.js'
import { ButtonGhostHover } from './button-ghost-hover.js'

const meta = {
  title: 'Design System/Button',
  component: ButtonPrimaryDefault,
  tags: ['autodocs'],
  parameters: {
    design: {
      type: 'figma',
      url: 'https://www.figma.com/design/uA3bE5ofr6BgRakJzudL4L/component?node-id=2-66',
    },
  },
} satisfies Meta<typeof ButtonPrimaryDefault>

export default meta

type Story = StoryObj<typeof meta>

export const PrimaryDefault: Story = {
  args: {
    buttonLabel: 'Button Label',
  },
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}

export const PrimaryHover: Story = {
  args: {
    buttonLabel: 'Button Label',
  },
  render: (args) => <ButtonPrimaryHover {...args} />,
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}

export const SecondaryDefault: Story = {
  args: {
    buttonLabel: 'Button Label',
  },
  render: (args) => <ButtonSecondaryDefault {...args} />,
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}

export const SecondaryHover: Story = {
  args: {
    buttonLabel: 'Button Label',
  },
  render: (args) => <ButtonSecondaryHover {...args} />,
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}

export const GhostDefault: Story = {
  args: {
    buttonLabel: 'Button Label',
  },
  render: (args) => <ButtonGhostDefault {...args} />,
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}

export const GhostHover: Story = {
  args: {
    buttonLabel: 'Button Label',
  },
  render: (args) => <ButtonGhostHover {...args} />,
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}
