/**
 * Generated by figma2react — do not edit; re-run to update.
 * Hand-written stories belong in input-field.custom.stories.tsx, which
 * is never overwritten.
 *
 * Each variant is still its own component, so only the first can be `meta.component`;
 * the rest render explicitly. Collapsing variants into one component with a
 * prop union would remove that, and is not implemented.
 */

import type { Meta, StoryObj } from '@storybook/react'
import { expectLayoutWithin } from './fidelity.js'
import { InputFieldDefault } from './input-field-default.js'
import { InputFieldHover } from './input-field-hover.js'
import { InputFieldFocused } from './input-field-focused.js'
import { InputFieldError } from './input-field-error.js'

const meta = {
  title: 'Design System/Input Field',
  component: InputFieldDefault,
  tags: ['autodocs'],
  parameters: {
    design: {
      type: 'figma',
      url: 'https://www.figma.com/design/uA3bE5ofr6BgRakJzudL4L/component?node-id=2-59',
    },
  },
} satisfies Meta<typeof InputFieldDefault>

export default meta

type Story = StoryObj<typeof meta>

export const Default: Story = {
  args: {
    placeholderText: 'Placeholder text',
  },
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}

export const Hover: Story = {
  args: {
    placeholderText: 'Placeholder text',
  },
  render: (args) => <InputFieldHover {...args} />,
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}

export const Focused: Story = {
  render: () => <InputFieldFocused inputValue="Input value" />,
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}

export const Error: Story = {
  render: () => <InputFieldError invalidInput="Invalid input" />,
  play: async ({ canvasElement }) => {
    await expectLayoutWithin(canvasElement, 4)
  },
}
