import { toUrlNodeId } from '@figma-to-react/core'
import type { ComponentEntry } from '@figma-to-react/emit-react'

/**
 * Generates CSF 3 stories from the manifest `emit()` returns.
 *
 * Deliberately consumes the manifest rather than the IR: the export names and
 * prop names it needs were decided during rendering, and re-deriving them here
 * would mean two implementations that must agree forever.
 */

export interface StoryOptions {
  fileKey: string
  /** Storybook title prefix for components that belong to a variant set. */
  titlePrefix?: string
  /**
   * Emit a fidelity play function per story. Only meaningful when the
   * components were generated with `traceIds`, since there is otherwise no
   * `data-figma-id` to measure against.
   */
  fidelity?: { threshold: number; helperPath: string }
}

export interface StoryFile {
  /** `button.stories.tsx`, relative to the output directory. */
  file: string
  source: string
}

/** One story file per variant set; standalone components get their own. */
export function emitStories(components: ComponentEntry[], options: StoryOptions): StoryFile[] {
  const groups = new Map<string, ComponentEntry[]>()
  for (const c of components) {
    const key = c.set ?? c.exportName
    groups.set(key, [...(groups.get(key) ?? []), c])
  }

  return [...groups.entries()].map(([key, entries]) => ({
    file: `${slug(key)}.stories.tsx`,
    source: renderStoryFile(key, entries, options),
  }))
}

function renderStoryFile(
  groupName: string,
  entries: ComponentEntry[],
  options: StoryOptions,
): string {
  const [primary, ...rest] = entries as [ComponentEntry, ...ComponentEntry[]]
  const grouped = primary.set !== undefined

  const imports = entries.map(
    (e) => `import { ${e.exportName} } from './${e.file.replace(/\.tsx$/, '.js')}'`,
  )
  if (options.fidelity) {
    imports.unshift(`import { expectLayoutWithin } from '${options.fidelity.helperPath}'`)
  }
  imports.unshift(`import type { Meta, StoryObj } from '@storybook/react'`)

  const title = `${options.titlePrefix ?? 'Design System'}/${groupName}`
  const header = grouped
    ? `/**
 * Generated by figma2react — do not edit; re-run to update.
 * Hand-written stories belong in ${slug(groupName)}.custom.stories.tsx, which
 * is never overwritten.
 *
 * Each variant is still its own component, so only the first can be \`meta.component\`;
 * the rest render explicitly. Collapsing variants into one component with a
 * prop union would remove that, and is not implemented.
 */`
    : `/**
 * Generated by figma2react — do not edit; re-run to update.
 * Hand-written stories belong in ${slug(groupName)}.custom.stories.tsx, which
 * is never overwritten.
 */`

  const meta = [
    `const meta = {`,
    `  title: ${quote(title)},`,
    `  component: ${primary.exportName},`,
    `  tags: ['autodocs'],`,
    `  parameters: {`,
    `    design: { type: 'figma', url: ${quote(figmaUrl(options.fileKey, primary.figmaId))} },`,
    `  },`,
    `} satisfies Meta<typeof ${primary.exportName}>`,
  ].join('\n')

  const primaryProps = new Set(primary.props.map((p) => p.name))
  const stories = entries.map((e, i) => renderStory(e, i === 0, primaryProps, options))
  void rest

  return (
    [
      header,
      imports.join('\n'),
      meta,
      `export default meta`,
      `type Story = StoryObj<typeof meta>`,
      ...stories,
    ].join('\n\n') + '\n'
  )
}

function renderStory(
  entry: ComponentEntry,
  isPrimary: boolean,
  primaryProps: Set<string>,
  options: StoryOptions,
): string {
  const name = entry.variant ? pascal(entry.variant) : 'Default'
  const body: string[] = []

  // `Story` is typed from `meta.component`, so `args` can only carry props that
  // component actually has. Variants often disagree: three input states whose
  // text layers are named `Placeholder text`, `Input value` and `Invalid input`
  // produce three different prop names. Where they diverge the values are
  // passed literally instead — the controls panel could not have driven them
  // under the meta's type either.
  const argsUsable = isPrimary || entry.props.every((p) => primaryProps.has(p.name))

  if (argsUsable && entry.props.length > 0) {
    const args = entry.props.map((p) => `    ${p.name}: ${quote(p.defaultValue)},`)
    body.push(`  args: {\n${args.join('\n')}\n  },`)
  }

  // Only the meta's own component renders implicitly from args.
  if (!isPrimary) {
    const props = argsUsable
      ? entry.props.length > 0
        ? ' {...args}'
        : ''
      : entry.props.map((p) => ` ${p.name}=${jsxAttr(p.defaultValue)}`).join('')
    // The parens are supplied here, so an unused parameter is the empty string
    // rather than `()` — which produced `render: (()) =>`.
    const params = argsUsable && entry.props.length > 0 ? 'args' : ''
    body.push(`  render: (${params}) => <${entry.exportName}${props} />,`)
  }

  if (options.fidelity) {
    body.push(
      `  play: async ({ canvasElement }) => {`,
      `    await expectLayoutWithin(canvasElement, ${options.fidelity.threshold})`,
      `  },`,
    )
  }

  return `export const ${name}: Story = {\n${body.join('\n')}\n}`
}

/**
 * Figma resolves a file by key alone, so the slug in the path is free — but the
 * node id has to be the URL form (`1-2`), not the API form (`1:2`).
 */
export function figmaUrl(fileKey: string, nodeId: string): string {
  return `https://www.figma.com/design/${fileKey}/component?node-id=${toUrlNodeId(nodeId)}`
}

const slug = (s: string) =>
  s
    .replace(/[^\p{L}\p{N}]+/gu, '-')
    .replace(/(\p{Ll})(\p{Lu})/gu, '$1-$2')
    .toLowerCase()
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-') || 'component'

const pascal = (s: string) => {
  const out = s
    .replace(/[^\p{L}\p{N}]+/gu, ' ')
    .trim()
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
  return /^\p{N}/u.test(out) ? `N${out}` : out || 'Default'
}

/** JSX attributes conventionally use double quotes; string literals do not. */
const jsxAttr = (s: string) => `"${s.replace(/"/g, '&quot;')}"`

const quote = (s: string) =>
  `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`
