import type { TokenManifest, TokenManifestEntry } from '@figma-to-react/core'

/**
 * Generates a Storybook story for the theme, plus the assertions that check it.
 *
 * The test is generated rather than hand-written for one reason: the design
 * decides how many assertions there are. Ten colours in the Figma file means
 * ten swatches and ten checked values, and adding an eleventh covers it without
 * anyone remembering to. A hand-written test drifts the moment the palette does.
 *
 * `emitStories` cannot express this — it is typed against `ComponentEntry[]` and
 * imports a component file per entry, and a token gallery has no component
 * behind it. Hence a sibling emitter rather than a fake entry.
 */

export interface ThemeStoryOptions {
  /** Storybook title, e.g. `Design System/Theme`. */
  title?: string
  /** Where `expectTokensRendered` lives, relative to the output directory. */
  helperPath?: string
  /** Emit the play function. Off leaves a gallery with no assertions. */
  assert?: boolean
}

export interface ThemeStoryFile {
  file: string
  source: string
}

const KIND_LABEL: Record<string, string> = {
  color: 'Colours',
  fontFamily: 'Typefaces',
  fontSize: 'Type scale',
  spacing: 'Spacing',
  radius: 'Radii',
  shadow: 'Shadows',
}

export function emitThemeStory(
  manifest: TokenManifest,
  options: ThemeStoryOptions = {},
): ThemeStoryFile {
  const title = options.title ?? 'Design System/Theme'
  const helper = options.helperPath ?? '../theme/assert.js'
  const assert = options.assert !== false

  const kinds = [...new Set(manifest.tokens.map((t) => t.kind))]
  const unnamed = manifest.tokens.filter((t) => !t.named).length
  const merged = manifest.tokens.filter((t) => designNames(t).length > 1)

  const imports = [`import type { Meta, StoryObj } from '@storybook/react'`]
  if (assert) imports.push(`import { expectTokensRendered } from '${helper}'`)

  const header = `/**
 * Generated by figma2react — do not edit; re-run to update.
 *
 * Every token in the theme, rendered so it can be looked at and measured. The
 * play function asserts the count first and the values second: a swatch missing
 * entirely is the failure a per-swatch loop would skip over.
 *${
   unnamed > 0
     ? `
 * ${unnamed} of ${manifest.tokens.length} tokens carry a name the generator derived from
 * the value rather than one a designer chose. Those are marked "derived" below,
 * and the design's own label for each is shown beside its custom property.`
     : ''
 }${
   merged.length > 0
     ? `
 *
 * ${merged.length} token(s) are MERGED: several design tokens share one value, and
 * with no names available they collapsed into a single custom property.
${merged.map((t) => ` *   ${t.cssVar} <- ${designNames(t).join(', ')}`).join('\n')}
 * They cannot be given different values until the design tells them apart.`
     : ''
 }
 */`

  const body = [
    header,
    imports.join('\n'),
    '',
    renderSwatchComponent(),
    '',
    `const meta = {
  title: '${title}',
  component: TokenGrid,
  // The global preview centres stories; a full-width grid wants the room.
  parameters: { layout: 'fullscreen' },
} satisfies Meta<typeof TokenGrid>

export default meta
type Story = StoryObj<typeof meta>`,
    '',
    ...kinds.map((kind) =>
      renderStory(
        kind,
        manifest.tokens.filter((t) => t.kind === kind),
        assert,
      ),
    ),
  ]

  return { file: 'theme.stories.tsx', source: `${body.filter(Boolean).join('\n')}\n` }
}

/**
 * One presentational component, rendered inline rather than imported, so the
 * story file stands alone — nothing else in the output directory has to exist
 * for it to compile.
 */
const renderSwatchComponent = () => `type TokenRow = {
  cssVar: string
  name: string
  value: string
  named: boolean
  kind: string
  /** What the design calls this — a Style/Variable name, or the id when unnamed. */
  design: string[]
}

function TokenGrid({ tokens = [] }: { tokens?: TokenRow[] }) {
  return (
    <div style={{ padding: 32, display: 'grid', gap: 16, gridTemplateColumns: 'repeat(auto-fill, minmax(190px, 1fr))' }}>
      {tokens.map((t) => (
        <figure key={t.cssVar} style={{ margin: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
          <div
            data-token={t.cssVar}
            data-token-value={t.value}
            data-token-named={String(t.named)}
            data-token-design={t.design.join(',')}
            style={
              t.kind === 'color'
                ? { height: 64, border: '1px solid rgb(0 0 0 / 0.1)', borderRadius: 4, background: \`var(\${t.cssVar})\` }
                : t.kind === 'radius'
                  ? // The swatch has to *use* the token, not merely sit beside
                    // it, or the assertion has nothing to measure.
                    { height: 64, border: '2px solid #334155', borderRadius: \`var(\${t.cssVar})\` }
                  : t.kind === 'spacing'
                    ? { height: 64, display: 'flex', alignItems: 'center' }
                    : { height: 64, border: '1px solid rgb(0 0 0 / 0.1)', borderRadius: 4, fontFamily: \`var(\${t.cssVar})\`, display: 'grid', placeItems: 'center' }
            }
          >
            {t.kind === 'spacing' ? (
              <span style={{ display: 'block', height: 12, background: '#334155', width: \`var(\${t.cssVar})\` }} />
            ) : t.kind === 'color' || t.kind === 'radius' ? null : (
              'Ag'
            )}
          </div>
          <figcaption style={{ fontSize: 12, lineHeight: 1.35 }}>
            <code style={{ fontFamily: 'ui-monospace, monospace' }}>{t.cssVar}</code>
            <div style={{ color: 'rgb(0 0 0 / 0.55)' }}>
              {t.design.length > 0 ? \`Figma: \${t.design.join(', ')}\` : 'not bound in Figma'}
            </div>
            <div style={{ color: 'rgb(0 0 0 / 0.6)' }}>{t.value}</div>
            {t.design.length > 1 ? (
              <div style={{ color: '#b91c1c' }}>
                merged — {t.design.length} design tokens share this value
              </div>
            ) : null}
            {t.named ? null : (
              <div style={{ color: '#b45309' }}>
                {t.design.length > 0
                  ? 'derived — bound, but the API withholds the name'
                  : 'derived — nothing bound, named by frequency'}
              </div>
            )}
          </figcaption>
        </figure>
      ))}
    </div>
  )
}`

function renderStory(kind: string, tokens: TokenManifestEntry[], assert: boolean): string {
  const rows = tokens
    .map(
      (t) =>
        `      { cssVar: '${t.cssVar}', name: '${t.name}', value: ${JSON.stringify(t.value)}, named: ${t.named}, kind: '${t.kind}', design: ${JSON.stringify(designNames(t))} },`,
    )
    .join('\n')

  // The expected set is baked in from the manifest, so `args.tokens.length` is
  // the count this design file produced — not whatever the page happens to show.
  const play = assert
    ? `
  play: async ({ canvasElement, args }) => {
    await expectTokensRendered(canvasElement, args.tokens ?? [])
  },`
    : ''

  return `
export const ${pascal(KIND_LABEL[kind] ?? kind)}: Story = {
  args: {
    tokens: [
${rows}
    ],
  },${play}
}`
}

/**
 * What the design calls a token, deduplicated.
 *
 * More than one entry means the collapse: several Figma Styles or Variables
 * resolved to the same value, and with no names available `collectTokens` keys
 * by value, so they merged into one custom property. `background` and `card`
 * both being white is not a reason to give an app one token — they have to be
 * free to diverge, which is exactly what a second theme mode asks of them.
 */
export function designNames(t: TokenManifestEntry): string[] {
  return [...new Set(t.sources.map((s) => s.name ?? s.key))]
}

const pascal = (s: string) =>
  s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join('')
