/**
 * Generated by figma2react — do not edit; re-run to update.
 *
 * Every token in the theme, rendered so it can be looked at and measured. The
 * play function asserts the count first and the values second: a swatch missing
 * entirely is the failure a per-swatch loop would skip over.
 *
 * 2 of 13 tokens carry a name the generator derived from
 * the value rather than one a designer chose. Those are marked "derived" below,
 * and the design's own label for each is shown beside its custom property.
 *
 * 2 token(s) are MERGED: several design tokens share one value, and
 * with no names available they collapsed into a single custom property.
 *   --color-primary <- VariableID:2:38, VariableID:2:32
 *   --color-primary-foreground <- VariableID:2:39, VariableID:2:33
 * They cannot be given different values until the design tells them apart.
 */
import type { Meta, StoryObj } from '@storybook/react'
import { expectTokensRendered } from '@figma-to-react/testing/theme'
type TokenRow = {
  cssVar: string
  name: string
  value: string
  named: boolean
  kind: string
  /** What the design calls this — a Style/Variable name, or the id when unnamed. */
  design: string[]
  /** The heading the design files this under. Absent when the design says none. */
  group?: string
}

function TokenGrid({ tokens = [] }: { tokens?: TokenRow[] }) {
  // Section per heading, in the order the tokens arrive — which is the order the
  // design puts them in. Tokens the design does not place fall into one
  // unlabelled section at the end rather than being reshuffled among the rest.
  const sections: { name?: string; tokens: TokenRow[] }[] = []
  for (const t of tokens) {
    const last = sections[sections.length - 1]
    if (last && last.name === t.group) last.tokens.push(t)
    else sections.push({ name: t.group, tokens: [t] })
  }

  return (
    <div style={{ padding: 32, display: 'flex', flexDirection: 'column', gap: 32 }}>
      {sections.map((section, i) => (
        <section key={section.name ?? i} data-token-group={section.name ?? ''}>
          {section.name ? (
            <h2
              style={{
                margin: '0 0 12px',
                fontSize: 13,
                fontWeight: 600,
                letterSpacing: '0.08em',
                textTransform: 'uppercase',
                color: 'rgb(0 0 0 / 0.55)',
              }}
            >
              {section.name}
            </h2>
          ) : null}
          <div
            style={{
              display: 'grid',
              gap: 16,
              gridTemplateColumns: 'repeat(auto-fill, minmax(190px, 1fr))',
            }}
          >
            {section.tokens.map((t) => (
              <figure
                key={t.cssVar}
                style={{ margin: 0, display: 'flex', flexDirection: 'column', gap: 8 }}
              >
                <div
                  data-token={t.cssVar}
                  data-token-value={t.value}
                  data-token-named={String(t.named)}
                  data-token-design={t.design.join(',')}
                  style={
                    t.kind === 'color'
                      ? {
                          height: 64,
                          border: '1px solid rgb(0 0 0 / 0.1)',
                          borderRadius: 4,
                          background: `var(${t.cssVar})`,
                        }
                      : t.kind === 'radius'
                        ? // The swatch has to *use* the token, not merely sit beside
                          // it, or the assertion has nothing to measure.
                          {
                            height: 64,
                            border: '2px solid #334155',
                            borderRadius: `var(${t.cssVar})`,
                          }
                        : t.kind === 'spacing'
                          ? { height: 64, display: 'flex', alignItems: 'center' }
                          : {
                              height: 64,
                              border: '1px solid rgb(0 0 0 / 0.1)',
                              borderRadius: 4,
                              fontFamily: `var(${t.cssVar})`,
                              display: 'grid',
                              placeItems: 'center',
                            }
                  }
                >
                  {t.kind === 'spacing' ? (
                    <span
                      style={{
                        display: 'block',
                        height: 12,
                        background: '#334155',
                        width: `var(${t.cssVar})`,
                      }}
                    />
                  ) : t.kind === 'color' || t.kind === 'radius' ? null : (
                    'Ag'
                  )}
                </div>
                <figcaption style={{ fontSize: 12, lineHeight: 1.35 }}>
                  <code style={{ fontFamily: 'ui-monospace, monospace' }}>{t.cssVar}</code>
                  <div style={{ color: 'rgb(0 0 0 / 0.55)' }}>
                    {t.design.length > 0 ? `Figma: ${t.design.join(', ')}` : 'not bound in Figma'}
                  </div>
                  <div style={{ color: 'rgb(0 0 0 / 0.6)' }}>{t.value}</div>
                  {t.design.length > 1 ? (
                    <div style={{ color: '#b91c1c' }}>
                      merged — {t.design.length} design tokens share this value
                    </div>
                  ) : null}
                  {t.named ? null : (
                    <div style={{ color: '#b45309' }}>
                      {t.design.length > 0
                        ? 'derived — bound, but the API withholds the name'
                        : 'derived — nothing bound, named by frequency'}
                    </div>
                  )}
                </figcaption>
              </figure>
            ))}
          </div>
        </section>
      ))}
    </div>
  )
}
const meta = {
  title: 'Design System/Theme',
  component: TokenGrid,
  // The global preview centres stories; a full-width grid wants the room.
  parameters: { layout: 'fullscreen' },
} satisfies Meta<typeof TokenGrid>

export default meta
type Story = StoryObj<typeof meta>

export const ColorPalette: Story = {
  args: {
    tokens: [
      {
        cssVar: '--color-primary',
        name: 'primary',
        value: '#2563eb',
        named: true,
        kind: 'color',
        design: ['VariableID:2:38', 'VariableID:2:32'],
        group: 'PRIMARY',
      },
      {
        cssVar: '--color-primary-foreground',
        name: 'primary-foreground',
        value: '#ffffff',
        named: true,
        kind: 'color',
        design: ['VariableID:2:39', 'VariableID:2:33'],
        group: 'PRIMARY',
      },
      {
        cssVar: '--color-neutral-0f',
        name: 'neutral-0f',
        value: '#0f172a',
        named: true,
        kind: 'color',
        design: ['VariableID:2:34'],
        group: 'NEUTRALS',
      },
      {
        cssVar: '--color-neutral-64',
        name: 'neutral-64',
        value: '#64748b',
        named: true,
        kind: 'color',
        design: [],
        group: 'NEUTRALS',
      },
      {
        cssVar: '--color-neutral-94',
        name: 'neutral-94',
        value: '#94a3b8',
        named: true,
        kind: 'color',
        design: ['VariableID:2:36'],
        group: 'NEUTRALS',
      },
      {
        cssVar: '--color-neutral-e2',
        name: 'neutral-e2',
        value: '#e2e8f0',
        named: true,
        kind: 'color',
        design: ['VariableID:2:37'],
        group: 'NEUTRALS',
      },
      {
        cssVar: '--color-neutral-f8',
        name: 'neutral-f8',
        value: '#f8fafc',
        named: true,
        kind: 'color',
        design: ['VariableID:2:40'],
        group: 'NEUTRALS',
      },
      {
        cssVar: '--color-neutral-ff',
        name: 'neutral-ff',
        value: '#ffffff',
        named: true,
        kind: 'color',
        design: [],
        group: 'NEUTRALS',
      },
      {
        cssVar: '--color-error',
        name: 'error',
        value: '#ef4444',
        named: true,
        kind: 'color',
        design: [],
        group: 'SEMANTIC',
      },
      {
        cssVar: '--color-success',
        name: 'success',
        value: '#22c55e',
        named: true,
        kind: 'color',
        design: ['Success'],
        group: 'SEMANTIC',
      },
      {
        cssVar: '--color-warning',
        name: 'warning',
        value: '#f59e0b',
        named: true,
        kind: 'color',
        design: ['Warning'],
        group: 'SEMANTIC',
      },
    ],
  },
  play: async ({ canvasElement, args }) => {
    await expectTokensRendered(canvasElement, args.tokens ?? [])
  },
}

export const Typefaces: Story = {
  args: {
    tokens: [
      {
        cssVar: '--font-inter',
        name: 'inter',
        value: 'Inter, ui-sans-serif, system-ui, sans-serif',
        named: false,
        kind: 'fontFamily',
        design: [],
      },
    ],
  },
  play: async ({ canvasElement, args }) => {
    await expectTokensRendered(canvasElement, args.tokens ?? [])
  },
}

export const Radii: Story = {
  args: {
    tokens: [
      {
        cssVar: '--radius-8',
        name: '8',
        value: '8px',
        named: false,
        kind: 'radius',
        design: ['VariableID:2:50'],
      },
    ],
  },
  play: async ({ canvasElement, args }) => {
    await expectTokensRendered(canvasElement, args.tokens ?? [])
  },
}
