/**
 * Generated by figma2react — do not edit; re-run to update.
 *
 * Every token in the theme, rendered so it can be looked at and measured. The
 * play function asserts the count first and the values second: a swatch missing
 * entirely is the failure a per-swatch loop would skip over.
 *
 * 8 of 8 tokens carry a name the generator derived from
 * the value rather than one a designer chose. Those are marked "derived" below.
 * The fix is a Figma Colour Style, not a different naming rule.
 */
import type { Meta, StoryObj } from '@storybook/react'
import { expectTokensRendered } from '@figma-to-react/testing/theme'
type TokenRow = {
  cssVar: string
  name: string
  value: string
  named: boolean
  kind: string
}

function TokenGrid({ tokens = [] }: { tokens?: TokenRow[] }) {
  return (
    <div
      style={{
        padding: 32,
        display: 'grid',
        gap: 16,
        gridTemplateColumns: 'repeat(auto-fill, minmax(190px, 1fr))',
      }}
    >
      {tokens.map((t) => (
        <figure
          key={t.cssVar}
          style={{ margin: 0, display: 'flex', flexDirection: 'column', gap: 8 }}
        >
          <div
            data-token={t.cssVar}
            data-token-value={t.value}
            data-token-named={String(t.named)}
            style={
              t.kind === 'color'
                ? {
                    height: 64,
                    borderRadius: 4,
                    border: '1px solid rgb(0 0 0 / 0.1)',
                    background: `var(${t.cssVar})`,
                  }
                : {
                    height: 64,
                    borderRadius: 4,
                    border: '1px solid rgb(0 0 0 / 0.1)',
                    fontFamily: `var(${t.cssVar})`,
                    display: 'grid',
                    placeItems: 'center',
                  }
            }
          >
            {t.kind === 'color' ? null : 'Ag'}
          </div>
          <figcaption style={{ fontSize: 12, lineHeight: 1.35 }}>
            <code style={{ fontFamily: 'ui-monospace, monospace' }}>{t.cssVar}</code>
            <div style={{ color: 'rgb(0 0 0 / 0.6)' }}>{t.value}</div>
            {t.named ? null : <div style={{ color: '#b45309' }}>derived — no Style bound</div>}
          </figcaption>
        </figure>
      ))}
    </div>
  )
}
const meta = {
  title: 'Design System/Theme',
  component: TokenGrid,
  // The global preview centres stories; a full-width grid wants the room.
  parameters: { layout: 'fullscreen' },
} satisfies Meta<typeof TokenGrid>

export default meta
type Story = StoryObj<typeof meta>

export const Colours: Story = {
  args: {
    tokens: [
      {
        cssVar: '--color-blue-200',
        name: 'blue-200',
        value: '#e2e8f0',
        named: false,
        kind: 'color',
      },
      {
        cssVar: '--color-blue-600',
        name: 'blue-600',
        value: '#2563eb',
        named: false,
        kind: 'color',
      },
      {
        cssVar: '--color-neutral-50',
        name: 'neutral-50',
        value: '#f8fafc',
        named: false,
        kind: 'color',
      },
      {
        cssVar: '--color-slate-400',
        name: 'slate-400',
        value: '#94a3b8',
        named: false,
        kind: 'color',
      },
      {
        cssVar: '--color-slate-600',
        name: 'slate-600',
        value: '#64748b',
        named: false,
        kind: 'color',
      },
      {
        cssVar: '--color-slate-950',
        name: 'slate-950',
        value: '#0f172a',
        named: false,
        kind: 'color',
      },
      { cssVar: '--color-white', name: 'white', value: '#ffffff', named: false, kind: 'color' },
    ],
  },
  play: async ({ canvasElement, args }) => {
    await expectTokensRendered(canvasElement, args.tokens ?? [])
  },
}

export const Typefaces: Story = {
  args: {
    tokens: [
      {
        cssVar: '--font-inter',
        name: 'inter',
        value: 'Inter, ui-sans-serif, system-ui, sans-serif',
        named: false,
        kind: 'fontFamily',
      },
    ],
  },
  play: async ({ canvasElement, args }) => {
    await expectTokensRendered(canvasElement, args.tokens ?? [])
  },
}
