import type {
  BoxStyle,
  IRNode,
  Layout,
  Shadow,
  TextStyle,
  TokenRef,
  TokenResolver,
} from '@figma-to-react/core'
import { NAMESPACE } from '@figma-to-react/core'

export interface CssContext {
  resolver: TokenResolver
  parent?: Layout
}

/** Collects plain CSS while TSX is rendered. Selectors are stable across runs. */
export class CssEmitter {
  private readonly rules = new Map<string, string[]>()
  constructor(private readonly scope: string) {}

  classFor(node: IRNode, ctx: CssContext, placement = false): string {
    const name = `f2r-${this.scope}-${slug(node.id)}`
    const declarations = placement
      ? placementDeclarations(node.layout, ctx)
      : declarationsFor(node, ctx)
    if (declarations.length) {
      const current = this.rules.get(name) ?? []
      this.rules.set(name, [...current, ...declarations])
    }
    return declarations.length ? name : ''
  }

  add(className: string, declarations: string[]): void {
    if (!className || declarations.length === 0) return
    const current = this.rules.get(className) ?? []
    this.rules.set(className, [...current, ...declarations])
  }

  css(): string {
    const rules = [...this.rules.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(
        ([name, declarations]) =>
          `.${name} {\n${[...new Set(declarations)].map((d) => `  ${d}`).join('\n')}\n}`,
      )
    return `/* Generated by figma2react - do not edit; re-run to update. */\n* , *::before, *::after { box-sizing: border-box; }\np, h1, h2, h3, figure { margin: 0; }\nbutton, input, textarea { margin: 0; font: inherit; color: inherit; }\nbutton { appearance: none; border: 0; }\n${rules.join('\n\n')}\n`
  }
}

export const scopeFor = (fileKey: string) => slug(fileKey).slice(0, 24) || 'design'
const slug = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
const px = (value: number) => `${round(value)}px`
const round = (value: number) => Math.round(value * 1000) / 1000

function declarationsFor(node: IRNode, ctx: CssContext): string[] {
  return [
    ...layoutDeclarations(node, ctx),
    ...boxDeclarations(node.box, ctx),
    ...(node.text ? textDeclarations(node.text, ctx) : []),
  ]
}

function placementDeclarations(layout: Layout, ctx: CssContext): string[] {
  const out: string[] = []
  if (ctx.parent?.mode === 'none' && layout.position) {
    out.push(
      'position: absolute;',
      `left: ${px(layout.position.x)};`,
      `top: ${px(layout.position.y)};`,
    )
  }
  if (layout.alignSelf) out.push(`align-self: ${align(layout.alignSelf)};`)
  out.push(...sizeDeclarations(layout, ctx, false))
  return out
}

function layoutDeclarations(node: IRNode, ctx: CssContext): string[] {
  const layout = node.layout
  const out: string[] = []
  if (layout.mode === 'none' && node.children.some((c) => c.layout.position))
    out.push('position: relative;')
  if (layout.mode === 'flex') {
    out.push('display: flex;')
    if (layout.direction === 'column') out.push('flex-direction: column;')
    if (layout.wrap) out.push('flex-wrap: wrap;')
    if (layout.justify) out.push(`justify-content: ${justify(layout.justify)};`)
    if (layout.align) out.push(`align-items: ${align(layout.align)};`)
    if (layout.gap)
      out.push(`gap: ${length(layout.gap.px, layout.gap.token, 'spacing', ctx.resolver)};`)
    if (layout.crossGap)
      out.push(
        `row-gap: ${length(layout.crossGap.px, layout.crossGap.token, 'spacing', ctx.resolver)};`,
      )
  }
  if (ctx.parent?.mode === 'none' && layout.position) {
    out.push(
      'position: absolute;',
      `left: ${px(layout.position.x)};`,
      `top: ${px(layout.position.y)};`,
    )
  }
  if (layout.alignSelf) out.push(`align-self: ${align(layout.alignSelf)};`)
  out.push(...sizeDeclarations(layout, ctx, node.kind === 'text'))
  if (layout.padding) {
    const p = layout.padding
    out.push(
      `padding: ${length(p.top.px, p.top.token, 'spacing', ctx.resolver)} ${length(p.right.px, p.right.token, 'spacing', ctx.resolver)} ${length(p.bottom.px, p.bottom.token, 'spacing', ctx.resolver)} ${length(p.left.px, p.left.token, 'spacing', ctx.resolver)};`,
    )
  }
  return out
}

function sizeDeclarations(layout: Layout, ctx: CssContext, text: boolean): string[] {
  const out: string[] = []
  const parentAxis = ctx.parent?.mode === 'flex' ? (ctx.parent.direction ?? 'row') : undefined
  if (layout.width.kind === 'fixed') out.push(`width: ${px(layout.width.px)};`)
  else if (layout.width.kind === 'fill')
    out.push(parentAxis === 'row' ? 'flex: 1 1 0%;' : 'width: 100%;')
  else if (text)
    out.push(
      layout.width.px === undefined ? 'width: max-content;' : `width: ${px(layout.width.px)};`,
    )
  if (layout.height.kind === 'fixed') out.push(`height: ${px(layout.height.px)};`)
  else if (layout.height.kind === 'fill')
    out.push(parentAxis === 'column' ? 'flex: 1 1 0%;' : 'height: 100%;')
  return out
}

function boxDeclarations(box: BoxStyle, ctx: CssContext): string[] {
  const out: string[] = []
  if (box.shape === 'ellipse') out.push('border-radius: 9999px;')
  if (box.fill?.kind === 'solid')
    out.push(`background: ${color(box.fill.color.css, box.fill.color.token, ctx.resolver)};`)
  if (box.fill?.kind === 'gradient') out.push(`background: ${box.fill.css};`)
  if (box.border) {
    const b = box.border
    if (b.sides) {
      for (const [side, width] of Object.entries(b.sides))
        if (width)
          out.push(
            `border-${side}: ${px(width)} ${b.style} ${color(b.color.css, b.color.token, ctx.resolver)};`,
          )
    } else
      out.push(
        `border: ${px(b.width)} ${b.style} ${color(b.color.css, b.color.token, ctx.resolver)};`,
      )
  }
  if (box.corners && box.shape !== 'ellipse') {
    const c = box.corners
    out.push(
      `border-radius: ${length(c.topLeft.px, c.topLeft.token, 'radius', ctx.resolver)} ${length(c.topRight.px, c.topRight.token, 'radius', ctx.resolver)} ${length(c.bottomRight.px, c.bottomRight.token, 'radius', ctx.resolver)} ${length(c.bottomLeft.px, c.bottomLeft.token, 'radius', ctx.resolver)};`,
    )
  }
  if (box.clip) out.push('overflow: hidden;')
  if (box.opacity !== undefined) out.push(`opacity: ${round(box.opacity)};`)
  if (box.shadows.length) out.push(`box-shadow: ${box.shadows.map((s) => shadow(s)).join(', ')};`)
  if (box.backdropBlur) out.push(`backdrop-filter: blur(${px(box.backdropBlur)});`)
  if (box.blur) out.push(`filter: blur(${px(box.blur)});`)
  return out
}

function textDeclarations(text: TextStyle, ctx: CssContext): string[] {
  const out: string[] = []
  if (text.fontFamily)
    out.push(
      `font-family: ${length(text.fontFamily.name, text.fontFamily.token, 'fontFamily', ctx.resolver)};`,
    )
  if (text.fontSize)
    out.push(
      `font-size: ${length(text.fontSize.px, text.fontSize.token, 'fontSize', ctx.resolver)};`,
    )
  if (text.lineHeightPx !== undefined) out.push(`line-height: ${px(text.lineHeightPx)};`)
  if (text.fontWeight !== undefined) out.push(`font-weight: ${text.fontWeight};`)
  if (text.italic) out.push('font-style: italic;')
  if (text.letterSpacing) out.push(`letter-spacing: ${px(text.letterSpacing)};`)
  if (text.align) out.push(`text-align: ${text.align};`)
  if (text.transform) out.push(`text-transform: ${text.transform};`)
  if (text.decoration) out.push(`text-decoration-line: ${text.decoration};`)
  if (text.color) out.push(`color: ${color(text.color.css, text.color.token, ctx.resolver)};`)
  return out
}

function color(value: string, token: TokenRef | undefined, resolver: TokenResolver): string {
  return length(value, token, 'color', resolver)
}
function length(
  value: string | number,
  token: TokenRef | undefined,
  kind: keyof typeof NAMESPACE,
  resolver: TokenResolver,
): string {
  const name = resolver.resolve(kind, value, token)
  if (name) return `var(${NAMESPACE[kind]}-${name})`
  return typeof value === 'number' ? px(value) : value
}
function shadow(s: Shadow): string {
  return `${s.inset ? 'inset ' : ''}${px(s.x)} ${px(s.y)} ${px(s.blur)} ${px(s.spread)} ${s.color.css}`
}
function justify(value: NonNullable<Layout['justify']>): string {
  return (
    { start: 'flex-start', center: 'center', end: 'flex-end', between: 'space-between' } as const
  )[value]
}
function align(value: NonNullable<Layout['align']> | NonNullable<Layout['alignSelf']>): string {
  return value === 'start' ? 'flex-start' : value === 'end' ? 'flex-end' : value
}
